# Generated by Django 2.0.6 on 2018-11-12 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0007_reflectionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildCardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('operating_budget', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=500, null=True)),
                ('number_of_employees', models.IntegerField(default=0)),
                ('established_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image_url', models.URLField(max_length=500, null=True)),
            ],
        ),
    ]
